### ISSUE TITLE
Bug: Panic after saving image

### ISSUE THREAD

**Issue by benjamin-voisin** [diamondburned/dissent#277]
Sometimes after trying to save an image, I get a panic and the app crash.
I have a hard time reproducing deterministically the bug, sometimes it works, sometimes it crashes. It seems that the issue arise when I change the default file name.
```
panic: given unknown closure user_data

goroutine 1 [running, locked to thread]:
github.com/diamondburned/gotk4/pkg/gtk/v4._gotk4_gtk4_NativeDialog_ConnectResponse(0xc000665780?, 0xfffffffd, 0x0?)
	github.com/diamondburned/gotk4/pkg@v0.2.2/gtk/v4/gtk_export.go:7736 +0xac
github.com/diamondburned/gotk4/pkg/gio/v2._Cfunc_g_application_run(0x62b0f0ebf160, 0x1, 0x62b0f0ec3af0)
	_cgo_gotypes.go:13799 +0x4f
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run.func3(0x62b0f0ebf160, 0x1, 0x62b0f0ec3af0)
	github.com/diamondburned/gotk4/pkg@v0.2.2/gio/v2/gio.go:41611 +0x67
github.com/diamondburned/gotk4/pkg/gio/v2.(*Application).Run(0xc000529aa0, {0xc000118140, 0x1, 0x1})
	github.com/diamondburned/gotk4/pkg@v0.2.2/gio/v2/gio.go:41611 +0x1f1
github.com/diamondburned/gotkit/app.(*Application).Run(0xc0003e2980, {0xc000118140, 0x1, 0x1})
	github.com/diamondburned/gotkit@v0.0.0-20240421051130-6094a5dcd206/app/app.go:272 +0x14f
github.com/diamondburned/gotkit/app.(*Application).RunMain(0x62b0ede79b28?)
	github.com/diamondburned/gotkit@v0.0.0-20240421051130-6094a5dcd206/app/app.go:277 +0x28
main.main()
	libdb.so/dissent/main.go:70 +0x6c5
```

**Comment by diamondburned** [comment]
https://github.com/diamondburned/dissent/commit/db3b1b001a39eb55d0ab18dc6b362c019aabe0fd should fix this. Could you try the latest pre-release?

**Comment by benjamin-voisin** [comment]
That seems to work !
Thank you for your reactivity
